name: 🐛 Bug Report
description: Report a bug or unexpected behavior in anyschema
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide a minimal code example that demonstrates the bug.
      placeholder: |
        ```python
        from anyschema import AnySchema

        # What code triggers the bug?
        ```
      render: python
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages or stack traces.
      placeholder: Paste error messages or describe what happened instead
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Please run `anyschema.show_versions()` and enter the output below
      description: |
        What library versions are you using?
        ```python
        import anyschema
        anyschema.show_versions()
        ```
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Any Additional Information
      description: Add any other context, screenshots, or information about the problem here.
      placeholder: Optional additional information

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched the existing issues to make sure this bug hasn't been reported yet
          required: true
        - label: I have provided a minimal reproducible example
          required: true
        - label: I am willing to submit a PR to fix this issue (optional)
