name: ✨ Feature Request
description: Suggest a new feature or enhancement for anyschema
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving anyschema!
        Please describe the feature you'd like to see added.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem or use case.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Provide a code example showing how you'd like to use this feature.
      placeholder: |
        ```python
        from anyschema import AnySchema

        # Example of how the feature would be used
        schema = AnySchema(spec=MyClass)
        result = schema.new_feature()
        ```
      render: python

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've considered using... but it doesn't work because...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute?
      options:
        - label: I am willing to submit a PR to implement this feature
        - label: I can help with design/testing
        - label: I can provide more examples or use cases

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched the existing issues to make sure this feature hasn't been requested yet
          required: true
        - label: I have checked the documentation to make sure this feature doesn't already exist
          required: true
